version: '2.1'

services:
  localstack:
    image: localstack/localstack
    ports:
      - 4566:4566
    environment:
      SERVICES: serverless
      LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT: 30
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - /var/run/docker.sock:/var/run/docker.sock
